import { describe, it, expect } from "vitest";
import { validateTWID, LETTER_MAP } from "@/lib/validators/twid";

/**
 * Fixtures below are synthetic but mathematically valid — they satisfy the
 * 戶政司 checksum formula documented in lib/validators/twid.ts. These are NOT
 * real, issued IDs; they're generated by running the algorithm in reverse for
 * a deterministic prefix. Using real citizens' IDs in test fixtures would
 * violate 個資法 (Personal Data Protection Act).
 *
 * To regenerate: for each valid citizen prefix "A1234567xx", pick the final
 * digit so total mod 10 = 0.
 */

const VALID_CITIZEN_IDS = [
  "A123456789", // canonical fixture — first letter A (臺北市)
  "B234567894", // 臺中市
  "H221234560", // 桃園市
  "F131232458", // 新北市
  "A234567893",
  "Z999999996", // edge case: all 9s
];

const INVALID_CITIZEN_IDS = [
  { id: "A123456788", reason: "checksum" as const }, // wrong check digit
  { id: "A12345678", reason: "length" as const }, // 9 chars
  { id: "A1234567890", reason: "length" as const }, // 11 chars
  { id: "1123456789", reason: "format" as const }, // leading digit
  { id: "AAAAAAAAAA", reason: "format" as const }, // all letters
  { id: "", reason: "length" as const },
];

const VALID_ARC_IDS = [
  // New format (2021+): 2 uppercase letters (2nd ∈ {A,B,C,D}) + 8 digits.
  "AB12345675",
  "FC00000008", // zeros edge case
  "AD98765431",
  "CC11111114",
];

const INVALID_ARC_IDS = [
  { id: "AE12345678", reason: "invalid-second-letter" as const }, // E not in A-D
  { id: "AB12345670", reason: "checksum" as const }, // wrong check digit
];

describe("validateTWID / citizen", () => {
  for (const id of VALID_CITIZEN_IDS) {
    it(`accepts ${id}`, () => {
      const r = validateTWID(id);
      expect(r.valid, `expected ${id} to be valid`).toBe(true);
      expect(r.type).toBe("citizen");
      expect(r.reason).toBeUndefined();
    });
  }

  for (const { id, reason } of INVALID_CITIZEN_IDS) {
    it(`rejects "${id}" with reason=${reason}`, () => {
      const r = validateTWID(id);
      expect(r.valid).toBe(false);
      expect(r.reason).toBe(reason);
    });
  }

  it("attaches region for valid IDs", () => {
    const r = validateTWID("A123456789");
    expect(r.region).toBe("臺北市");
  });

  it("is case-insensitive on first letter", () => {
    const upper = validateTWID("A123456789");
    const lower = validateTWID("a123456789");
    expect(upper.valid).toBe(lower.valid);
    expect(upper.raw).toBe("A123456789");
    expect(lower.raw).toBe("A123456789");
  });
});

describe("validateTWID / new-format ARC (2021+)", () => {
  for (const id of VALID_ARC_IDS) {
    it(`accepts ${id}`, () => {
      const r = validateTWID(id);
      expect(r.valid, `expected ${id} to be valid`).toBe(true);
      expect(r.type).toBe("arc-new");
    });
  }

  for (const { id, reason } of INVALID_ARC_IDS) {
    it(`rejects ${id} with reason=${reason}`, () => {
      const r = validateTWID(id);
      expect(r.valid).toBe(false);
      expect(r.reason).toBe(reason);
    });
  }
});

describe("LETTER_MAP integrity", () => {
  it("has all 26 letters mapped", () => {
    const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
    for (const l of letters) {
      expect(LETTER_MAP[l], `missing letter ${l}`).toBeGreaterThanOrEqual(10);
      expect(LETTER_MAP[l], `out-of-range letter ${l}`).toBeLessThanOrEqual(35);
    }
  });

  it("is immutable at runtime", () => {
    expect(Object.isFrozen(LETTER_MAP)).toBe(true);
  });

  it("matches the published 戶政司 table for spot-checked entries", () => {
    // These specific values are defined by 內政部戶政司 and must never change.
    expect(LETTER_MAP.A).toBe(10);
    expect(LETTER_MAP.B).toBe(11);
    expect(LETTER_MAP.I).toBe(34);
    expect(LETTER_MAP.O).toBe(35);
    expect(LETTER_MAP.W).toBe(32);
    expect(LETTER_MAP.Z).toBe(33);
  });
});
